from __future__ import annotations

from email.message import EmailMessage
from pathlib import Path
import argparse
import hashlib
import json
import os
import smtplib
import ssl
import urllib.parse
import urllib.request


DEFAULT_SMTP_HOST = "smtp.gmail.com"
DEFAULT_SMTP_PORT = 587
MAX_TELEGRAM_MATCHES = 10


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Send Telegram and Gmail alerts for matching flight monitor results."
    )
    parser.add_argument(
        "--report",
        required=True,
        help="Path to the JSON report generated by japan_flight_monitor.py.",
    )
    parser.add_argument(
        "--state-file",
        required=True,
        help="Path to a file used to remember the last notified match set.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Build and print the notification message without sending it.",
    )
    return parser.parse_args()


def load_report(report_path: str) -> dict:
    with open(report_path, "r", encoding="utf-8") as handle:
        return json.load(handle)


def compute_signature(matches: list[dict]) -> str:
    payload = json.dumps(matches, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def load_previous_signature(state_path: Path) -> str | None:
    if not state_path.exists():
        return None
    return state_path.read_text(encoding="utf-8").strip() or None


def save_signature(state_path: Path, signature: str) -> None:
    state_path.parent.mkdir(parents=True, exist_ok=True)
    state_path.write_text(signature, encoding="utf-8")


def require_env(name: str) -> str:
    value = os.environ.get(name, "").strip()
    if not value:
        raise RuntimeError(f"Missing required environment variable: {name}")
    return value


def build_plaintext_message(report: dict, matches: list[dict], run_url: str) -> str:
    lines = [
        "Flight alert: threshold match found",
        f"Scanned at: {report['scan_time']} (Asia/Manila)",
        f"Threshold: PHP {report['min_price']:,} to PHP {report['max_price']:,}",
        f"Matches found: {len(matches)}",
        "",
    ]

    for index, match in enumerate(matches, start=1):
        lines.append(
            f"{index}. PHP {match['price_php']:,} | {match['airline']} | "
            f"{match['origin']} -> {match['destination']}"
        )
        if match.get("details"):
            lines.append(f"   Details: {match['details']}")
        lines.append(f"   Source: {match['source_url']}")
        lines.append("")

    if report.get("failures"):
        lines.append("Warnings:")
        for failure in report["failures"]:
            lines.append(f"- {failure}")
        lines.append("")

    if run_url:
        lines.append(f"Workflow run: {run_url}")
    return "\n".join(lines).strip()


def build_telegram_message(report: dict, matches: list[dict], run_url: str) -> str:
    visible_matches = matches[:MAX_TELEGRAM_MATCHES]
    lines = [
        "Flight alert",
        f"Scan: {report['scan_time']}",
        f"Range: PHP {report['min_price']:,} to PHP {report['max_price']:,}",
        f"Matches: {len(matches)}",
        "",
    ]

    for index, match in enumerate(visible_matches, start=1):
        lines.append(
            f"{index}. PHP {match['price_php']:,} | {match['airline']} | "
            f"{match['origin']} -> {match['destination']}"
        )
        if match.get("details"):
            lines.append(f"   {match['details']}")

    if len(matches) > MAX_TELEGRAM_MATCHES:
        lines.append("")
        lines.append(f"Plus {len(matches) - MAX_TELEGRAM_MATCHES} more matches in email/workflow output.")

    if run_url:
        lines.append("")
        lines.append(f"Run: {run_url}")

    message = "\n".join(lines).strip()
    if len(message) > 3900:
        return message[:3850] + "\n...\nRun: " + run_url
    return message


def send_telegram(text: str) -> None:
    token = require_env("TELEGRAM_BOT_TOKEN")
    chat_id = require_env("TELEGRAM_CHAT_ID")
    payload = urllib.parse.urlencode({"chat_id": chat_id, "text": text}).encode("utf-8")
    request = urllib.request.Request(
        f"https://api.telegram.org/bot{token}/sendMessage",
        data=payload,
        method="POST",
    )
    with urllib.request.urlopen(request, timeout=20) as response:
        body = response.read().decode("utf-8", errors="replace")
    if '"ok":true' not in body:
        raise RuntimeError(f"Telegram API returned an unexpected response: {body}")


def send_email(subject: str, body: str) -> None:
    smtp_username = require_env("GMAIL_SMTP_USERNAME")
    smtp_password = require_env("GMAIL_SMTP_APP_PASSWORD")
    recipient = require_env("NOTIFY_EMAIL_TO")
    smtp_host = os.environ.get("GMAIL_SMTP_HOST", DEFAULT_SMTP_HOST)
    smtp_port = int(os.environ.get("GMAIL_SMTP_PORT", str(DEFAULT_SMTP_PORT)))

    message = EmailMessage()
    message["Subject"] = subject
    message["From"] = smtp_username
    message["To"] = recipient
    message.set_content(body)

    context = ssl.create_default_context()
    with smtplib.SMTP(smtp_host, smtp_port, timeout=30) as smtp:
        smtp.starttls(context=context)
        smtp.login(smtp_username, smtp_password)
        smtp.send_message(message)


def main() -> int:
    args = parse_args()
    report = load_report(args.report)
    matches = report.get("matches", [])
    if not matches:
        print("No threshold matches in this run. No notifications sent.")
        return 0

    signature = compute_signature(matches)
    state_path = Path(args.state_file)
    previous_signature = load_previous_signature(state_path)
    if previous_signature == signature:
        print("Matches are unchanged from the last notification. Skipping alert.")
        return 0

    run_url = os.environ.get("GITHUB_RUN_URL", "").strip()
    email_body = build_plaintext_message(report, matches, run_url)
    telegram_body = build_telegram_message(report, matches, run_url)

    if args.dry_run:
        print("Dry run mode: notifications were not sent.")
        print()
        print(email_body)
        return 0

    subject = (
        f"Flight alert: {len(matches)} match(es) in PHP "
        f"{report['min_price']:,}-{report['max_price']:,}"
    )
    send_telegram(telegram_body)
    send_email(subject, email_body)
    save_signature(state_path, signature)
    print("Telegram and email notifications sent.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())